In [18]:
#adjustments to the transcripts file
import os
import pandas as pd
input_folder = '/home/davids/main/projects/Segger_final/input_for_segger/'

for sample in os.listdir(input_folder):
    print(sample)
    transcripts_df = pd.read_parquet(f'{input_folder}{sample}/transcripts.parquet')
    transcripts_df.to_csv(f'{input_folder}{sample}/transcripts_for_proseg.csv', index=False)

33156-Slide-1_B1-2
33156-Slide-1_B2-2
33156-Slide-5_C2-2
33156-Slide-5_A2-1
33156-Slide-22_D1-1
33156-Slide-5_B2-1
33156-Slide-22_C1-1
33156-Slide-22_B2-1
33156-Slide-22_B1-1
33156-Slide-22_A1-1
33156-Slide-1_A1-1
33156-Slide-1_B1-1
33156-Slide-22_A2-1
33156-Slide-1_D2-1
33156-Slide-22_D2-1
33156-Slide-1_A2-2
33156-Slide-5_D1-2
33156-Slide-5_A1-2
33156-Slide-1_C2-1
33156-Slide-1_A2-3
33156-Slide-5_B1-3
33156-Slide-22_C2-1
33156-Slide-5_C1-1

In [16]:
#adjustments to the transcripts file
import os
import pandas as pd
input_folder = '/home/davids/main/projects/Segger_final/input_for_segger/'

for sample in os.listdir(input_folder):
    print(sample)
    transcripts_df = pd.read_parquet(f'{input_folder}{sample}/transcripts.parquet')
    new_transcripts_df = pd.DataFrame({
        "feature_name": transcripts_df["gene"].values.astype(str),
        "x_location": transcripts_df["global_x"].values.astype("int64"),
        "y_location": transcripts_df["global_y"].values.astype("int64"),
        "z_location": transcripts_df["global_z"].values.astype("int64"),
        "cell_id": transcripts_df["EntityID"].values.astype("int64"),
        "transcript_id": transcripts_df["transcript_id"].values.astype("int64"),
        "overlaps_nucelus": transcripts_df["overlaps_nucleus"].values.astype(bool),
        "gene": transcripts_df["gene"].values.astype(str)
    })

    new_transcripts_df.to_csv(f'{input_folder}{sample}/transcripts_for_proseg.csv', index=False)

33156-Slide-1_B1-2
33156-Slide-1_B2-2
33156-Slide-5_C2-2
33156-Slide-5_A2-1
33156-Slide-22_D1-1
33156-Slide-5_B2-1
33156-Slide-22_C1-1
33156-Slide-22_B2-1
33156-Slide-22_B1-1
33156-Slide-22_A1-1
33156-Slide-1_A1-1
33156-Slide-1_B1-1
33156-Slide-22_A2-1
33156-Slide-1_D2-1
33156-Slide-22_D2-1
33156-Slide-1_A2-2
33156-Slide-5_D1-2
33156-Slide-5_A1-2
33156-Slide-1_C2-1
33156-Slide-1_A2-3
33156-Slide-5_B1-3
33156-Slide-22_C2-1
33156-Slide-5_C1-1

In [ ]:
import subprocess

output_folder = "/home/davids/main/projects/proseg/no_SC/"
for sample in os.listdir(input_folder):

    command = [

        "proseg", 
        "--merscope",
        "--nthreads", "16",
        "--min-qv", "0",
        "--output-path", f"{output_folder}{sample}/",
        "--overwrite",
        "--enforce-connectivity",
        f"{input_folder}{sample}/transcripts_for_proseg.csv"
    ]

    # 3. Run it
    my_env = os.environ.copy()
    my_env["CUDA_VISIBLE_DEVICES"] = "1"
    try:
        print(f"Running Proseg on {sample}...")
        result = subprocess.run(
            command, 
            env=my_env,      # Pass the GPU environment here
            check=True, 
            capture_output=True, 
            text=True
        )
        print("Success!")
    except subprocess.CalledProcessError as e:
        print(f"Error: {e.stderr}")

33156-Slide-1_B1-2
Running Proseg on 33156-Slide-1_B1-2...
Success!
33156-Slide-1_B2-2
Running Proseg on 33156-Slide-1_B2-2...
Success!
33156-Slide-5_C2-2
Running Proseg on 33156-Slide-5_C2-2...
Success!
33156-Slide-5_A2-1
Running Proseg on 33156-Slide-5_A2-1...
Success!
33156-Slide-22_D1-1
Running Proseg on 33156-Slide-22_D1-1...
Success!
33156-Slide-5_B2-1
Running Proseg on 33156-Slide-5_B2-1...
Success!
33156-Slide-22_C1-1
Running Proseg on 33156-Slide-22_C1-1...
Success!
33156-Slide-22_B2-1
Running Proseg on 33156-Slide-22_B2-1...

In [14]:
proseg_tx = pd.read_csv('/home/davids/main/projects/Segger_final/input_for_segger/33156-Slide-22_D1-1/transcripts_for_proseg.csv')

In [15]:
proseg_tx.head()

,feature_name,x_location,y_location,z_location,cell_id,transcript_id,overlaps_nucelus
0,Esrrg,434,1756,39,-1,0,False
1,Esrrg,963,1277,39,367,1,True
2,Esrrg,15,1438,40,-1,2,False
3,Esrrg,563,1292,40,-1,3,False
4,Esrrg,980,1268,40,367,4,True

In [1]:
import pandas as pd

tx = pd.read_csv('/home/davids/main/sds/sd22c003/mi_spatialomics_project/MI_ApoE/Molecular_Cartography/segger_test/UNSERE_merscope_formatted_data_test/detected_transcripts.csv')

In [7]:
tx.dtypes

overlaps_nucleus      bool
transcript_id        int64
cell_id              int64
EntityID             int64
x_location           int64
y_location           int64
z_location           int64
feature_name        object
dtype: object

In [2]:
tx.head()

,overlaps_nucleus,transcript_id,cell_id,EntityID,x_location,y_location,z_location,feature_name
0,True,0,14248,14248,1361,1776,17,Esrrg
1,False,1,-1,-1,1319,1322,18,Esrrg
2,False,2,-1,-1,1326,1746,18,Esrrg
3,False,3,-1,-1,1948,2102,18,Esrrg
4,False,4,-1,-1,1689,811,19,Esrrg

In [5]:
raw_tx = pd.read_parquet('/home/davids/main/projects/Segger_final/input_for_segger/33156-Slide-22_D1-1/transcripts.parquet')
raw_tx.head()

,global_x,global_y,global_z,gene,overlaps_nucleus,transcript_id,cell_id,EntityID
0,434,1756,39,Esrrg,False,0,-1,-1
1,963,1277,39,Esrrg,True,1,367,367
2,15,1438,40,Esrrg,False,2,-1,-1
3,563,1292,40,Esrrg,False,3,-1,-1
4,980,1268,40,Esrrg,True,4,367,367